### ISSUE TITLE
Don't set IMAGE_FEATURES in machine configuration

### ISSUE THREAD

**Issue by rossburton** [ADLINK/meta-adlink-ampere#3]
```
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
```

Don't do that.

**Comment by dineshkumarv86** [comment]
Issue has been resolved in below commit 
https://github.com/ADLINK/meta-adlink-ampere/commit/c5dcde09c4676667780ac9961307bfac94b6aa1c
