### ISSUE TITLE
create scarthgap branch

### ISSUE THREAD

**Issue by luca-fancellu** [ADLINK/meta-adlink-ampere#35]
It would be great to have a scarthgap branch and allow downstream projects to use it.

**Comment by luca-fancellu** [comment]
Any news on this?

**Comment by kkraman02** [comment]
Scarthgap yet to be developed. It will be started by Jan 2025.

**Comment by kkraman02** [comment]
@diego-sueiro, unfortunately we're only focused on LTS version release this year onwards.

**Comment by diego-sueiro** [comment]
@kkraman02 , any updates on when the scarthgap branch will be created?
