### ISSUE TITLE
Don't force systemd

### ISSUE THREAD

**Issue by rossburton** [ADLINK/meta-adlink-ampere#6]
https://github.com/ADLINK/meta-adlink-ampere/blob/main/conf/machine/include/ampere.inc#L19

```
DISTRO_FEATURES_append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
```

The machine BSP has no need to force the init system used.  Don't do this in the BSP.

**Comment by dineshkumarv86** [comment]
Issue has been resolved in below commit 
https://github.com/ADLINK/meta-adlink-ampere/commit/c5dcde09c4676667780ac9961307bfac94b6aa1c
